[package]
name = "foo_bl"
version = "0.1.0"
authors = ["Amit Upadhyay <upadhyay@gmail.com>"]
edition = "2018"

[dependencies]
amitu_base = "0.1.0"
diesel = { version = "1.4.2", features = ["postgres", "chrono"] }
failure = "0.1.5"
chrono = "0.4.7"
lazy_static = "1.2.0"
regex = "1"
